---
title: "Music Insights"
author: "Connor Kurland"
output:
  html_document:
    df_print: paged
---

First, we need tidyverse to handle data importing and wrangling...

```{R}
#suppressMessages(install.packages("tidyverse"))
suppressMessages(library(tidyverse))

#avoid absolute paths
#use relative paths (can use URLs)
survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")

preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")

```

Number of rows
```{R}
nrow(survey)
```

Column names
```{R}
colnames(survey)
```

Levels
```{R}
levels(survey)
```
Number of rows
```{R}
nrow(preferences)
```

Column names
```{R}
colnames(preferences)
```

Levels
```{R}
levels(preferences)
```

Cleaning data frame column names:
```{R}
colnames(survey)[colnames(survey)=="First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <-"generator_name"
colnames(survey)[colnames(survey)=="What is your pseudonym"] <- "pseudonym"
```


new Functions to use:
strsplit()
parse_datetime()

Here we are going to change all column names to something workable and consistent for the dataset survey:
```{R}
colnames(survey)[colnames(survey)=="Timestamp"] <- "time_submitted"

colnames(survey)[colnames(survey)=="generator_name"] <- "pseudonym_generator"

colnames(survey)[colnames(survey)=="What is your pseudonym?"] <- "pseudonym"

colnames(survey)[colnames(survey)=="Sex"] <- "sex"

colnames(survey)[colnames(survey)=="Major"] <- "academic_major"

colnames(survey)[colnames(survey)=="Academic Year"] <- "academic_level"

colnames(survey)[colnames(survey)=="Year you were born (YYYY)"] <- "year_born"

colnames(survey)[colnames(survey)=="Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument_list"

colnames(survey)[colnames(survey)=="Artist"] <- "favorite_song_artist"

colnames(survey)[colnames(survey)=="Song"] <- "favorite_song"

colnames(survey)[colnames(survey)=="Link to song (on Youtube or Vimeo)"] <- "favorite_song_link"
```


Loading two more libraries:
```{R}
library(dplyr)
library(tidyr)
```

in dplyr and tidyr cheat sheet dplyr::data_frame is deprecated, use tibbles

Creating the Person table:
```{R}
person <- tibble(time_submitted=survey$time_submitted,pseudonym_generator=survey$pseudonym_generator,pseudonym=survey$pseudonym,sex=survey$sex,academic_major=survey$academic_major,academic_level=survey$academic_level,year_born=survey$year_born,favorite_song=survey$favorite_song)
```

Create the Favorite Song table:
```{R}
favorite_song <- tibble(pseudonym=survey$pseudonym,favorite_song=survey$favorite_song,favorite_song_artist=survey$favorite_song_artist,favorite_song_link=survey$favorite_song_link)
```

A dataset is tidy if:
1) 1 column per variable
2) 1 row per observation
3) cohesive table

```{R}
library(readr)
```

Cleaned up the time submitted data in the person table
```{R}
person$time_submitted <- as.POSIXlt(parse_datetime(person$time_submitted,format="%m/%d/%y %H:%M"))
```

Categorical variables should be represented as factors:
Sex, academic_major, academic_year

Making the categorical variables to factors in person
```{R}
person$academic_level <- as.factor(person$academic_level)
person$academic_major <- as.factor(person$academic_major)
person$sex <- as.factor(person$sex)
```

Viewing the levels of the categorical variables in person
```{R}
levels(person$academic_level)
levels(person$sex)
```
Consolidating the two different CINS names into one in person
```{R}
levels(person$academic_major)[levels(person$academic_major)=="Computer information systems"] <- "Computer Information Systems"
levels(person$academic_major)
```

Adjusting the column names of the preference table
```{R}
colnames(preferences)[colnames(preferences)=="Timestamp"] <- "time_submitted"
colnames(preferences)[colnames(preferences)=="What was your pseudonym?"] <- "pseudonym"
```

Create the ratings table. First I use the gather function to create a table, rating_switch, with the artist_song and rating as rows not columns. This makes the data tidy. I then create the rating table by using all the columns except time_submitted from rating_switch
```{R}
rating_switch <- gather(preferences,"artist_song","rating",3:45)
ratings <- tibble(pseudonym=rating_switch$pseudonym, artist_song=rating_switch$artist_song, rating=rating_switch$rating)
```


Creating a isual representation of the ratings table
```{R}
(rate_box <- ggplot(data=rating, aes(x=artist_song,y=rating)) + geom_boxplot())
```

In Class:
```{R}
ggplot(ratings, aes(x=rating)) + geom_histogram(binwidth=1)
```


to apply limits on x and y axis: xlim(_,_) or ylim(_,_)
can set stuff to element_blank() to remove from graph
```{R}
ggplot(ratings, aes(x=pseudonym,y=rating)) + geom_boxplot() + theme_light()
```

person's rating of each song

```{R}
```



